services:
  - type: web
    name: fastapi-sqlite-app
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend:app --host 0.0.0.0 --port 10000"
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
